"""
Streamlit app for running a multi-agent research workflow.

This app provides a user interface for configuring, starting, monitoring,
and downloading reports generated by a multi-agent AI system. Users can
select LLM type, set workflow parameters, and view real-time progress and logs.
"""

import asyncio
import datetime
import html
import os
import queue
import threading
import time
from dataclasses import asdict
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
import requests
import streamlit as st

# Import your existing classes
from llm_factory import DEFAULTS
from multi_agent_workflow import (
    LLMType,
    MultiAgentWorkflow,
    WorkflowConfig,
    build_default_research_profile,
)
from research_profiles import get_research_profile_options

load_dotenv()


@st.cache_data(show_spinner=False, ttl=30)
def get_local_ollama_models(base_url: str) -> list[str]:
    """Return local Ollama model names exposed by the Ollama API."""
    try:
        response = requests.get(f"{base_url.rstrip('/')}/api/tags", timeout=2)
        response.raise_for_status()
        payload = response.json()

        models = [
            model.get("name", "").strip()
            for model in payload.get("models", [])
            if isinstance(model, dict) and model.get("name")
        ]
        return sorted(models)
    except (requests.RequestException, ValueError, TypeError, AttributeError):
        return []


# Configure Streamlit page
st.set_page_config(
    page_title="Multi-Agent Research",
    page_icon="🔎",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Custom CSS for better styling
st.markdown(
    """
<style>
    :root {
        --app-bg: #f7f8fa;
        --surface: #ffffff;
        --surface-muted: #fafafa;
        --border: #e5e7eb;
        --text: #111827;
        --muted: #6b7280;
        --accent: #111827;
        --accent-soft: rgba(17, 24, 39, 0.06);
        --success: #0f766e;
        --warning: #b45309;
        --danger: #b91c1c;
    }

    .stApp {
        background:
            radial-gradient(circle at top left, rgba(17, 24, 39, 0.04), transparent 30%),
            linear-gradient(180deg, #fbfbfc 0%, var(--app-bg) 100%);
        color: var(--text);
    }

    .main .block-container {
        max-width: 1180px;
        padding-top: 1.6rem;
        padding-bottom: 2.4rem;
    }

    [data-testid="stSidebar"] {
        background: var(--surface);
        border-right: 1px solid var(--border);
    }

    .main-header {
        padding: 1.4rem 1.5rem;
        background: rgba(255, 255, 255, 0.78);
        border: 1px solid var(--border);
        border-radius: 22px;
        box-shadow: 0 10px 30px rgba(15, 23, 42, 0.04);
        margin-bottom: 1.25rem;
    }

    .main-header .eyebrow {
        font-size: 0.74rem;
        font-weight: 700;
        letter-spacing: 0.16em;
        text-transform: uppercase;
        color: var(--muted);
        margin-bottom: 0.45rem;
    }

    .main-header h1 {
        margin: 0;
        font-size: 2.1rem;
        line-height: 1.05;
        letter-spacing: -0.05em;
        color: var(--text);
    }

    .main-header p {
        margin: 0.55rem 0 0;
        max-width: 52rem;
        color: var(--muted);
        font-size: 1rem;
        line-height: 1.6;
    }

    .summary-card {
        height: 100%;
        padding: 1rem 1.1rem;
        background: var(--surface);
        border: 1px solid var(--border);
        border-radius: 18px;
        box-shadow: 0 1px 2px rgba(15, 23, 42, 0.04);
    }

    .summary-card__label {
        font-size: 0.72rem;
        font-weight: 700;
        letter-spacing: 0.14em;
        text-transform: uppercase;
        color: var(--muted);
        margin-bottom: 0.55rem;
    }

    .summary-card__value {
        font-size: 1.06rem;
        font-weight: 650;
        line-height: 1.35;
        color: var(--text);
    }

    .summary-card__detail {
        margin-top: 0.4rem;
        color: var(--muted);
        font-size: 0.92rem;
        line-height: 1.5;
    }

    .agent-status,
    .tool-result,
    .success-box,
    .error-box {
        padding: 0.9rem 1rem;
        border-radius: 16px;
        margin: 0.75rem 0;
        background: var(--surface);
        border: 1px solid var(--border);
        box-shadow: 0 1px 2px rgba(15, 23, 42, 0.04);
        color: var(--text);
    }

    .agent-status {
        border-left: 3px solid var(--accent);
    }

    .tool-result {
        border-left: 3px solid #1d4ed8;
    }

    .success-box {
        border-left: 3px solid var(--success);
    }

    .error-box {
        border-left: 3px solid var(--danger);
    }

    .stButton > button {
        border-radius: 999px;
        border: 1px solid var(--border);
        background: var(--surface);
        color: var(--text);
        font-weight: 600;
        transition: border-color 0.18s ease, background-color 0.18s ease,
            color 0.18s ease, box-shadow 0.18s ease;
    }

    .stButton > button:hover {
        border-color: var(--accent);
        color: var(--accent);
        box-shadow: 0 4px 16px rgba(15, 23, 42, 0.06);
    }

    .stButton > button[kind="primary"] {
        background: var(--accent);
        border-color: var(--accent);
        color: #ffffff;
    }

    .stButton > button[kind="primary"]:hover {
        background: #0f172a;
        border-color: #0f172a;
        color: #ffffff;
    }
</style>
""",
    unsafe_allow_html=True,
)

# Initialize session state
if "workflow_running" not in st.session_state:
    st.session_state.workflow_running = False
if "workflow_results" not in st.session_state:
    st.session_state.workflow_results = []
if "config" not in st.session_state:
    st.session_state.config = None
if "workflow_stop_requested" not in st.session_state:
    st.session_state.workflow_stop_requested = False
if "active_profile_title" not in st.session_state:
    st.session_state.active_profile_title = "Built-in default"
if "active_profile_topic" not in st.session_state:
    st.session_state.active_profile_topic = "General research"
if "selected_llm_name" not in st.session_state:
    st.session_state.selected_llm_name = "OpenAI"
if "selected_llm_model" not in st.session_state:
    st.session_state.selected_llm_model = "Provider default"


def render_summary_card(label: str, value: str, detail: str = "") -> None:
    """Render a compact dashboard-style summary card."""
    detail_html = (
        f'<div class="summary-card__detail">{html.escape(detail)}</div>'
        if detail
        else ""
    )
    st.markdown(
        f"""
        <div class="summary-card">
            <div class="summary-card__label">{html.escape(label)}</div>
            <div class="summary-card__value">{html.escape(value)}</div>
            {detail_html}
        </div>
        """,
        unsafe_allow_html=True,
    )


def create_sidebar() -> Optional[WorkflowConfig]:
    """Create the configuration sidebar"""
    st.sidebar.title("Configuration")
    try:
        profile_options = get_research_profile_options()
        configured_profile_path = os.getenv("RESEARCH_PROFILE_PATH")
        default_index = 0
        configured_profile_found = False

        if configured_profile_path:
            configured_path = Path(configured_profile_path)
            if not configured_path.is_absolute():
                configured_path = Path(__file__).resolve().parent / configured_path

            resolved_configured_path = configured_path.resolve()
            for index, option in enumerate(profile_options):
                if (
                    option.path
                    and Path(option.path).resolve() == resolved_configured_path
                ):
                    default_index = index
                    configured_profile_found = True
                    break

            if not configured_profile_found:
                st.sidebar.warning(
                    f"Configured profile not found: {configured_profile_path}. Using the built-in default."
                )
        selected_profile = st.sidebar.selectbox(
            "Research Profile",
            options=profile_options,
            index=default_index,
            format_func=lambda option: option.label,
            help="Choose the topic profile used to prefill prompts, source tiers, and report defaults.",
        )
        active_profile = selected_profile.profile
        st.session_state.active_profile_title = active_profile.title
        st.session_state.active_profile_topic = active_profile.topic
    except (FileNotFoundError, ValueError) as exc:
        st.sidebar.error(f"Could not load research profiles: {exc}")
        active_profile = build_default_research_profile()
        selected_profile = None
        st.session_state.active_profile_title = active_profile.title
        st.session_state.active_profile_topic = active_profile.topic

    profile_state_key = (
        selected_profile.path
        if selected_profile and selected_profile.path
        else "builtin_default"
    )
    profile_state_key = (
        profile_state_key.replace("\\", "_").replace("/", "_").replace(":", "_")
    )

    # LLM Configuration
    llm_options = [llm_type.name for llm_type in LLMType]
    llm_name = st.sidebar.selectbox(
        "LLM",
        options=llm_options,
        index=0,
        help="Select the language model to use",
    )
    # Convert back to enum for config
    llm_enum = LLMType[llm_name]
    llm_model = None

    if llm_enum == LLMType.OLLAMA:
        ollama_host = os.getenv("OLLAMA_HOST", "http://localhost:11434")
        ollama_models = get_local_ollama_models(ollama_host)

        if ollama_models:
            current_model = st.session_state.get("ollama_model_select")
            default_index = (
                ollama_models.index(current_model)
                if current_model in ollama_models
                else 0
            )
            llm_model = st.sidebar.selectbox(
                "Ollama Model",
                options=ollama_models,
                index=default_index,
                help="Pick one of the models available in your local Ollama instance.",
                key="ollama_model_select",
            )
        else:
            st.sidebar.warning(
                "No local Ollama models were found. Make sure Ollama is running and at least one model is pulled."
            )
            llm_model = st.sidebar.text_input(
                "Ollama Model",
                value=DEFAULTS["ollama_model"],
                help="Fallback when Ollama cannot be queried yet.",
                key="ollama_model_input",
            )

    # Report Configuration
    st.sidebar.subheader("Report settings")
    target_word_count = st.sidebar.slider(
        "Target Word Count",
        min_value=1000,
        max_value=10000,
        value=active_profile.target_word_count,
        step=500,
        help="Target length for the generated report",
        key=f"{profile_state_key}_target_word_count",
    )

    min_developments = st.sidebar.slider(
        "Minimum Developments",
        min_value=1,
        max_value=10,
        value=active_profile.min_developments,
        help="Minimum number of developments to include",
        key=f"{profile_state_key}_min_developments",
    )

    max_developments = st.sidebar.slider(
        "Maximum Developments",
        min_value=1,
        max_value=15,
        value=active_profile.max_developments,
        help="Maximum number of developments to include",
        key=f"{profile_state_key}_max_developments",
    )

    # File Configuration
    st.sidebar.subheader("File settings")
    docs_dir = st.sidebar.text_input(
        "Output Directory", value="./docs", help="Directory where reports will be saved"
    )

    report_filename = st.sidebar.text_input(
        "Report Filename",
        value=active_profile.default_report_filename,
        help="Base filename for the report (timestamp will be added)",
        key=f"{profile_state_key}_report_filename",
    )

    # Workflow Configuration
    st.sidebar.subheader("Workflow settings")
    max_iterations = st.sidebar.slider(
        "Max Iterations",
        min_value=1,
        max_value=20,
        value=10,
        help="Maximum number of iterations before stopping",
    )

    timeout_seconds = (
        st.sidebar.slider(
            "Timeout (minutes)",
            min_value=5,
            max_value=60,
            value=30,
            help="Maximum time to run the workflow",
        )
        * 60
    )  # Convert to seconds

    # Logging Configuration
    log_level = st.sidebar.selectbox(
        "Log level",
        options=["DEBUG", "INFO", "WARNING", "ERROR"],
        index=1,
        help="Logging verbosity level",
    )

    # Trusted Sources Configuration
    st.sidebar.subheader("Trusted sources")
    with st.sidebar.expander("Edit Source Tiers"):
        primary_sources_text = st.text_area(
            "Primary sources (one per line)",
            value="\n".join(active_profile.primary_sources),
            height=170,
            help="Use these first for claims, statistics, trial results, and dates.",
            key=f"{profile_state_key}_primary_sources_text",
        )

        secondary_sources_text = st.text_area(
            "Secondary sources (one per line)",
            value="\n".join(active_profile.secondary_sources),
            height=220,
            help="Use these for discovery or context. Verify key claims against a primary source.",
            key=f"{profile_state_key}_secondary_sources_text",
        )

        primary_sources = [
            s.strip() for s in primary_sources_text.split("\n") if s.strip()
        ]
        secondary_sources = [
            s.strip() for s in secondary_sources_text.split("\n") if s.strip()
        ]
        trusted_sources = [*primary_sources, *secondary_sources]

    st.session_state.selected_llm_name = llm_name
    st.session_state.selected_llm_model = llm_model or "Provider default"

    # Create configuration object
    try:
        config = WorkflowConfig(
            tavily_api_key=os.getenv("TAVILY_API_KEY", ""),
            llm_type=llm_enum,  # Pass enum value as before
            llm_model=llm_model if llm_enum == LLMType.OLLAMA else None,
            research_profile_path=selected_profile.path if selected_profile else None,
            docs_dir=docs_dir,
            default_report_filename=report_filename,
            target_word_count=target_word_count,
            min_developments=min_developments,
            max_developments=max_developments,
            max_iterations=max_iterations,
            timeout_seconds=timeout_seconds,
            primary_sources=primary_sources,
            secondary_sources=secondary_sources,
            trusted_sources=trusted_sources,
            log_level=log_level,
        )
        st.session_state.config = config
        return config
    except (FileNotFoundError, ValueError) as e:
        st.sidebar.error(f"Configuration Error: {e}")
        return None


def display_workflow_status(event_queue):
    """Display real-time workflow status"""
    status_container = st.container()

    with status_container:
        if not event_queue.empty():
            try:
                while not event_queue.empty():
                    event_data = event_queue.get_nowait()
                    timestamp = event_data.get(
                        "timestamp", datetime.datetime.now()
                    ).strftime("%H:%M:%S")

                    if event_data["type"] == "agent_change":
                        st.markdown(
                            f"""
                        <div class="agent-status">
                            🤖 <strong>Agent:</strong> {event_data['agent']} 
                            (Iteration {event_data['iteration']})
                        </div>
                        """,
                            unsafe_allow_html=True,
                        )

                    elif event_data["type"] == "agent_output":
                        if event_data["content"]:
                            st.write("📤 **Output:**", event_data["content"])
                        if event_data["tool_calls"]:
                            st.write(
                                "🛠️ **Planning to use tools:**",
                                event_data["tool_calls"],
                            )

                    elif event_data["type"] == "tool_result":
                        st.markdown(
                            f"""
                        <div class="tool-result">
                            🔧 <strong>Tool Result ({event_data['tool_name']}):</strong><br>
                            <strong>Arguments:</strong> {event_data['arguments']}<br>
                            <strong>Output:</strong> {event_data['output'][:200]}...
                        </div>
                        """,
                            unsafe_allow_html=True,
                        )

                    elif event_data["type"] == "tool_call":
                        st.write(f"🔨 **Calling Tool:** {event_data['tool_name']}")
                        st.write(f"**Arguments:** {event_data['arguments']}")

                    elif event_data["type"] == "cancelled":
                        st.markdown(
                            f"""
                        <div class="error-box">
                            <small>{timestamp}</small><br>
                            ⏹️ <strong>Cancelled:</strong> {event_data['message']}
                        </div>
                        """,
                            unsafe_allow_html=True,
                        )

                    elif event_data["type"] == "timed_out":
                        st.markdown(
                            f"""
                        <div class="error-box">
                            <small>{timestamp}</small><br>
                            ⏱️ <strong>Timed Out:</strong> {event_data['message']}
                        </div>
                        """,
                            unsafe_allow_html=True,
                        )

                    elif event_data["type"] == "completion":
                        st.markdown(
                            f"""
                        <div class="success-box">
                            <small>{timestamp}</small><br>
                            ✅ <strong>Completed:</strong> {event_data['message']}
                        </div>
                        """,
                            unsafe_allow_html=True,
                        )

                    elif event_data["type"] == "error":
                        st.markdown(
                            f"""
                        <div class="error-box">
                            <small>{timestamp}</small><br>
                            ❌ <strong>Error:</strong> {event_data['message']}
                        </div>
                        """,
                            unsafe_allow_html=True,
                        )

                    # Store in session state for persistence
                    if (
                        not st.session_state.workflow_results
                        or st.session_state.workflow_results[-1] != event_data
                    ):
                        st.session_state.workflow_results.append(event_data)

            except queue.Empty:
                pass


async def run_workflow_async(config, event_queue, cancel_event):
    """Run the workflow asynchronously and capture events"""
    try:
        workflow = MultiAgentWorkflow(config)

        async for event in workflow.stream_runtime_events(
            cancel_requested=cancel_event.is_set
        ):
            event_queue.put(event.to_payload())

    # Catch all exceptions during workflow initialization to ensure proper error reporting
    except Exception as e:  # pylint: disable=broad-exception-caught
        event_queue.put(
            {
                "type": "error",
                "message": f"Workflow initialization failed: {str(e)}",
                "timestamp": datetime.datetime.now(),
            }
        )


def run_workflow_in_thread(config, event_queue, cancel_event):
    """Run the async workflow in a separate thread"""
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        loop.run_until_complete(run_workflow_async(config, event_queue, cancel_event))
    finally:
        # Cancel all pending tasks before closing the loop
        pending = asyncio.all_tasks(loop)
        for task in pending:
            task.cancel()
        loop.run_until_complete(asyncio.gather(*pending, return_exceptions=True))
        loop.close()


def main():
    """Main Streamlit application"""
    # Header
    st.markdown(
        """
    <div class="main-header">
        <div class="eyebrow">Multi-agent research workspace</div>
        <h1>Multi-Agent Research</h1>
        <p>Configure a profile, run the workflow, and review progress in a calm dashboard layout.</p>
    </div>
    """,
        unsafe_allow_html=True,
    )

    # Create sidebar configuration
    config = create_sidebar()

    summary_col1, summary_col2, summary_col3 = st.columns(3)
    with summary_col1:
        render_summary_card(
            "Profile",
            st.session_state.active_profile_title,
            st.session_state.active_profile_topic,
        )
    with summary_col2:
        render_summary_card(
            "Model",
            st.session_state.selected_llm_name,
            st.session_state.selected_llm_model,
        )
    with summary_col3:
        render_summary_card(
            "State",
            "Running" if st.session_state.workflow_running else "Idle",
            (
                "Stop requested"
                if st.session_state.workflow_stop_requested
                else f"{len(st.session_state.workflow_results)} event(s) captured"
            ),
        )

    # Main content area
    col1, col2 = st.columns([2, 1])

    with col1:
        st.subheader("Workflow control")

        # Display current configuration
        if config:
            with st.expander("Current configuration", expanded=False):
                config_dict = asdict(config)
                for key, value in config_dict.items():
                    if key != "tavily_api_key":  # Don't display API key
                        st.write(f"**{key}:** {value}")

        # Control buttons
        col_start, col_stop, col_clear = st.columns(3)

        with col_start:
            start_button = st.button(
                "Start workflow",
                disabled=st.session_state.workflow_running or config is None,
                help="Start the multi-agent research workflow",
                type="primary",
                use_container_width=True,
            )

        with col_stop:
            stop_button = st.button(
                "Stop workflow",
                disabled=not st.session_state.workflow_running,
                help="Stop the currently running workflow",
                use_container_width=True,
            )

        with col_clear:
            clear_button = st.button(
                "Clear log",
                help="Clear all workflow results and logs",
                use_container_width=True,
            )

        # Handle button clicks
        if start_button and config:
            st.session_state.workflow_running = True
            st.session_state.workflow_stop_requested = False
            st.session_state.workflow_results = []

            cancel_event = threading.Event()

            # Create event queue for communication
            event_queue = queue.Queue()

            # Start workflow in background thread
            workflow_thread = threading.Thread(
                target=run_workflow_in_thread, args=(config, event_queue, cancel_event)
            )
            workflow_thread.daemon = True
            workflow_thread.start()

            # Store thread and queue in session state
            st.session_state.workflow_thread = workflow_thread
            st.session_state.event_queue = event_queue
            st.session_state.cancel_event = cancel_event

            st.success("🚀 Workflow started! Monitor progress below.")
            st.rerun()

        if stop_button:
            st.session_state.workflow_stop_requested = True
            if hasattr(st.session_state, "cancel_event"):
                st.session_state.cancel_event.set()
            st.warning(
                "⏹️ Stop requested. The workflow will halt at the next safe interruption point."
            )
            st.rerun()

        if clear_button:
            st.session_state.workflow_results = []
            st.info("🗑️ Results cleared.")
            st.rerun()

    with col2:
        st.subheader("Status")

        if st.session_state.workflow_running:
            with st.spinner("Workflow is running. Please wait..."):
                if st.session_state.workflow_stop_requested:
                    st.markdown("**Status:** Stop requested")
                else:
                    st.markdown("**Status:** Running")
                st.markdown(
                    "**Started:** " + datetime.datetime.now().strftime("%H:%M:%S")
                )
        else:
            st.markdown("**Status:** Stopped")

        # Display report files
        if config and Path(config.docs_dir).exists():
            st.subheader("Generated reports")
            report_files = list(Path(config.docs_dir).glob("*.md"))

            if report_files:
                for file_path in sorted(report_files, reverse=True):
                    file_name = file_path.name
                    file_size = file_path.stat().st_size
                    mod_time = datetime.datetime.fromtimestamp(
                        file_path.stat().st_mtime
                    )

                    with st.expander(file_name):
                        st.write(f"**Size:** {file_size} bytes")
                        st.write(
                            f"**Modified:** {mod_time.strftime('%Y-%m-%d %H:%M:%S')}"
                        )

                        # Download button
                        with open(file_path, "r", encoding="utf-8") as f:
                            content = f.read()

                        st.download_button(
                            label="⬇️ Download",
                            data=content,
                            file_name=file_name,
                            mime="text/markdown",
                        )
            else:
                st.info("No reports generated yet")

    # Workflow Results Section
    st.subheader("Workflow progress")

    # Auto-refresh when workflow is running
    if st.session_state.workflow_running and hasattr(st.session_state, "event_queue"):
        display_workflow_status(st.session_state.event_queue)

        # Check if workflow thread is still alive
        if hasattr(st.session_state, "workflow_thread"):
            if not st.session_state.workflow_thread.is_alive():
                terminal_event = next(
                    (
                        result
                        for result in reversed(st.session_state.workflow_results)
                        if result["type"]
                        in {"cancelled", "timed_out", "error", "completion"}
                    ),
                    None,
                )
                st.session_state.workflow_running = False
                st.session_state.workflow_stop_requested = False

                if terminal_event and terminal_event["type"] == "cancelled":
                    st.warning(f"⏹️ {terminal_event['message']}")
                elif terminal_event and terminal_event["type"] == "timed_out":
                    st.warning(f"⏱️ {terminal_event['message']}")
                elif terminal_event and terminal_event["type"] == "error":
                    st.error(f"❌ {terminal_event['message']}")
                else:
                    success_message = (
                        terminal_event["message"]
                        if terminal_event and terminal_event["type"] == "completion"
                        else "Workflow completed successfully"
                    )
                    st.success(f"✅ {success_message}")

        # Auto-refresh every 2 seconds when running
        time.sleep(2)
        st.rerun()

    # Display historical results
    if st.session_state.workflow_results:
        st.subheader("Workflow log")

        # Display results in reverse chronological order
        # Show last 20
        for result in reversed(st.session_state.workflow_results[-20:]):
            timestamp = result.get("timestamp", datetime.datetime.now()).strftime(
                "%H:%M:%S"
            )

            if result["type"] == "agent_change":
                st.markdown(
                    f"""
                <div class="agent-status">
                    <small>{timestamp}</small><br>
                    🤖 <strong>Agent:</strong> {result['agent']} (Iteration {result['iteration']})
                </div>
                """,
                    unsafe_allow_html=True,
                )

            elif result["type"] == "completion":
                st.markdown(
                    f"""
                <div class="success-box">
                    <small>{timestamp}</small><br>
                    ✅ <strong>Completed:</strong> {result['message']}
                </div>
                """,
                    unsafe_allow_html=True,
                )

            elif result["type"] == "error":
                st.markdown(
                    f"""
                <div class="error-box">
                    <small>{timestamp}</small><br>
                    ❌ <strong>Error:</strong> {result['message']}
                </div>
                """,
                    unsafe_allow_html=True,
                )

            elif result["type"] == "cancelled":
                st.markdown(
                    f"""
                <div class="error-box">
                    <small>{timestamp}</small><br>
                    ⏹️ <strong>Cancelled:</strong> {result['message']}
                </div>
                """,
                    unsafe_allow_html=True,
                )

            elif result["type"] == "timed_out":
                st.markdown(
                    f"""
                <div class="error-box">
                    <small>{timestamp}</small><br>
                    ⏱️ <strong>Timed Out:</strong> {result['message']}
                </div>
                """,
                    unsafe_allow_html=True,
                )


if __name__ == "__main__":
    main()
